name: Build APK (Unsigned)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Unsigned APK
      uses: actions/upload-artifact@v3@99f97e7f913da0ef5a768eabf3bb4a7e27127d00
      with:
        name: unsigned-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
